### ISSUE TITLE
New feature - delete old backups

### ISSUE THREAD

**Issue by shayzalman** [tecrahul/mydumpadmin#2]
That will be nice to have it as part of the bash script

**Comment by claymore008** [comment]
Yes, rotation is always welcome!

**Comment by tecrahul** [comment]
Added option to remove older backups from local system.

**Comment by claymore008** [comment]
### Remove older backups
This function `rm -rf ${DBDELDATE}` will not work, because the format of directory is "YYYYMMDD-hhmm"
